# Generated by Django 5.1 on 2024-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(choices=[('Savanes', 'Savanes'), ('Kara', 'Kara'), ('Centrale', 'Centrale'), ('Plateau', 'Plateau'), ('Maritime', 'Maritime'), ('Grand Lomé', 'Grand Lomé')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_identite/')),
            ],
        ),
    ]
